- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: enable nginx 1.24
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: Remove the entire directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create the nhtml  directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download frontend
    ansible.builtin.get_url: #ansible module for downloading the file
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip 
      dest: /tmp/frontend.zip

  - name: unarchieve frontend
    ansible.builtin.unarchive:
     src: /tmp/frontend.zip
     dest: /usr/share/nginx/html
     remote_src: yes

  - name: Remove the default nginx
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent

  - name: copy the nginx.conf
    ansible.builtin.template:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: restart the nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes

      #login to the server and check if the url reflecting correct in the conf. example-> cat /etc/nginx/nginx.conf

