- name: mngodb configure
  hosts: mongodb
  become: yes
  tasks:
  - name:
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install mongodb server
    ansible.builtin.dnf:   #for installing if we use one os we use same for all servers and install use dnf for rhel
     name: mongodb-org
     state: present

  - name: allow remote connections    
    ansible.builtin.replace: #replace listen addresses in the config file
     path: /etc/mongod.conf
     regexp: '127.0.0.1'
     repalce: '0.0.0.0'

  - name: start and enable mongodb
    ansible.builtin.service:  #for services starting and enabling
      name: mongod
      enabled: yes
      state: started

  # - name: restart mongodb
  #   ansible.builtin.service:  #for services starting and enabling
  #     name: mongodb
  #     state: restarted