- name: create ec2 and route 53 records
  hosts: all
  connection: local
  vars:
   sg_id: sg-028a0f9feae2f961e
   ami_id: ami-0220d79f3f480ecf5
   domain_name: siddharthais.online
   env: dev
   instances:
   - mongodb
   - catalogue 
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
     instance_type: "t3.micro"
     security_group: "{{ sg_id }}"
     image_id: "{{ ami_id }}"
     name: "{{ item }}-{{ env }}"
     tags:
       Project: roboshop
       Component: "{{ item }}"
       Environment: "{{ env }}"
       Name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the output
    ansible.builtin.debug:
     msg: "{{ ec2_output }}"

  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}-{{ domain_name }}" #mongodb-dev.siddharthais.online
      type: A
      ttl: 7200
      value: 1.1.1.1,2.2.2.2,3.3.3.3
      wait: true
    loop: "{{ ec2_output.results }}"