- name: configure shipping server
  hosts: shipping
  become: yes
  tasks:
  - name: install maven and mysql
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql

  - name: create system user roboshop
    ansible.builtin.user: #for creating user with ansible module
     name: roboshop
     system: true
     home: /app
     shell: /sbin/nologin
     comment: " Roboshop System user "

  - name: delete app directory
    ansible.builtin.file:  #for deleting directories with ansible module
     path: /app
     state: absent

  - name: create app directory
    ansible.builtin.file:  #for creating directories with ansible module
      path: /app
      state: directory

  - name: delete shipping zip file
    ansible.builtin.file:  #ansible module for delete  the file
      dest: /tmp/shipping.zip  
      state: absent 

  - name: download shipping
    ansible.builtin.get_url: #ansible module for downloading the file
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
      dest: /tmp/shipping.zip

  - name: unarchieve shipping
    ansible.builtin.unarchive:
     src: /tmp/shipping.zip
     dest: /app
     remote_src: yes

  - name: install dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app    #to move to the app directory to run the command install the dependencies here

  - name: install dependencies
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args:
      chdir: /app    #to move to the app directory to run the command install the dependencies here

  - name: create systemctl service
    ansible.builtin.template:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: demonreload
    ansible.builtin.systemd_service:
     daemon_reload: true
  
  - name: install dependencies
    ansible.builtin.pip:
      name: PyMySQL
      excutable: pip3.9
    args:
      chdir: /app

  - name: import shipping data   
    community.mysql.mysql_db:   #anisble command to import the data
      state: import
      name: all
      login_host: "{{ MYSQL_HOST }}"
      login_user: root
      login_password: RoboShop@1
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql

  - name: start and enable shipping
    ansible.builtin.service:
      name: shipping
      state: restarted
      enabled: yes